### ISSUE TITLE
Open file/line in an IDE

### ISSUE THREAD

**Issue by pmartin** [crew-cr/Crew#10]
_(I am not the one doing the review, but the one who is trying to fix what's been written as comments during the review)_

When I am on the "diff" screen, and have a comment on a file+line, I generally want to open that file in my IDE, on the line where the comment is, to fix it.

It would be really useful if each line in crew had a link formatted so clicking on it would trigger the opening of the right file, at the right line, in the IDE.

<br>
In crew, you'd have to:
- Generate a link with a specific protocol, like `phpide://`
- Include the file path and line

For example, a link could look like this : `phpide:///path/to/my/project/web/my-file.php@65`

Then, it's only a matter of _(on the developper's computer, not in crew)_:
- Configuring the browser so the `phpide://` protocol is associated with a specific script
- Creating that script so it launches the IDE, passing it the file name and line

Couple of points:
- In crew, you don't know the full path to the file on the dev's computer ; just use a local one, and let the script on the developper's computer transform it to an absolute one
- Passing the branch's name in the URI might be usefull to _(the script could then use it to determine the absolute path)_

<br />
Note: this is definitely possible -- see the `xdebug.file_link_format` option for Xdebug on http://xdebug.org/docs/stack_trace , for instance.

**Comment by tentacode** [comment]
As each project path on each dev computer is potentially different you have to configure it on a per project basis.

It could be somewhere in the (non existing yet) user panel.
