### ISSUE TITLE
Empty Repository?

### ISSUE THREAD

**Issue by Naatan** [crew-cr/Crew#114]
Hi, I just stumbled upon this awesome project and quickly got it installed. Everything seems to be working properly, except that when I add my repository, it doesn't seem to be detecting it's contents. It just shows up as empty.

The only installation issue I see is that the sample apache config refers to the following path:

/path/to/your/workspace/Crew/cache/packed

Except the 'packed' directory does not exist for me.

I checked the logs dir but did not see anything created.

Are there any troubleshooting steps I can follow?

Thanks

**Comment by ratibus** [comment]
Hi

The packed directory is created on-the-fly. If the application looks like the screenshots you've seen, the packed directory works fine :)

About the repository, Crew shows you only the branches that are not merged into their base branch. That could explain the empty repository.

Did you notice some errors in the admin page, in the Log Git table ? If not, your installation seems to be fine.

Regards

**Comment by ghost** [comment]
I'm having the same problem on Debian and Windows 7.
I get it set up properly and clone a repo but it just shows up empty. I have several branches not merged into master so that isn't the problem.
This is the screen I'm getting if it helps:
http://i.imgur.com/Pkxgs.png
That's a fresh install with a clone of Twitter's Bootstrap straight from Github.

**Comment by ratibus** [comment]
Did you call the REST API for these unmerged branches (https://github.com/pmsipilot/Crew/wiki/API) ?
Unmerged branches do not show up automatically on Crew. It has to be requested by one user to appear.

**Comment by KuiKui** [comment]
You can also use this [shell script](https://github.com/pmsipilot/Crew/blob/master/scripts/review-request.sh) to make a _Review Request_.
