### ISSUE TITLE
No branch

### ISSUE THREAD

**Issue by obazoud** [crew-cr/Crew#118]
Hello,

I have installed and configured Crew from master (7eb548a5eb9ed7160124571efc589544b5b899e4).
I added some projets from github and these are no problems. Barre repo is present on filesystem.

But I can not see branches. All my projets have no branch in Crew, however branches really exists.
In MySQL, branch table is still empty.

I don't find a way to add branches.

Any ideas ? tips ?

Best regards,
Olivier.

**Comment by srogier** [comment]
Did you use the API (https://github.com/pmsipilot/Crew/wiki/Reviews-API) to create a review request on your branch ?

**Comment by srogier** [comment]
You'll have some answers in this issue : https://github.com/pmsipilot/Crew/issues/114

**Comment by obazoud** [comment]
Yes, and the answer is 
 curl -X POST --data "base_branch=master&branch=develop&commit=0d34cd8c6ec69c74955100e1fdfc07bf9cdb6ba6" http://crew/crew/api.php/projects/5/reviews

{"message":"Unknown branch 'develop' in project 'git-external"}

**Comment by srogier** [comment]
Do you see an error in the  admin.php/ page (there is a tooltip on the error code).

Maybe your apache user don't have write access on your git repository.

**Comment by obazoud** [comment]
I create /opt/repositories with www-data user.
And it contains bare repository that Crew clones.

**Comment by ratibus** [comment]
If you go in this bare repository, do you see your develop branch when you make a "git branch" command ?

**Comment by obazoud** [comment]
Results with two projects I impoted in Crew:

```
/opt/repositories/git-external$ git branch
  01_branch
  02_clean_before_add_a_new_path
  03_cmd
  04_status
  05_configuration
* develop
  gh-pages
  master
```

Develop is the default branch in this project.

```
/opt/repositories/Jenkins-Khan$ git branch
  gh-pages
* master
  refactoring_api
```

```
/opt/repositories$ ll
total 16
drwxr-xr-x 4 www-data root     4096 Oct  5 14:36 ./
drwxr-xr-x 6 root     root     4096 Oct  5 13:21 ../
drwxr-xr-x 7 www-data www-data 4096 Oct  5 15:17 git-external/
drwxr-xr-x 7 www-data www-data 4096 Oct  5 14:24 Jenkins-Khan/
```

**Comment by ratibus** [comment]
Can you tell us what are the new records in the admin page when you make your curl call ?
Every git command is logged in this page with return code and output message.

**Comment by obazoud** [comment]
```
0    git --git-dir='/opt/repositories/git-external' branch --no-merged 'master' | grep 'develop' | sed "s/ //g" 2>&1
0    git --git-dir='/opt/repositories/git-external' fetch -p origin 2>&1
0    git clone --mirror 'git://github.com/pmsipilot/Jenkins-Khan.git' '/opt/repositories/Jenkins-Khan' 2>&1
0    git clone --mirror 'git://github.com/obazoud/git-external.git' '/opt/repositories/git-external' 2>&1
```

**Comment by KuiKui** [comment]
Your `develop` branch is probably already merged in your base branch `master`.

**Comment by ratibus** [comment]
As Kuikui said, in Crew, you only see the branches that are both unmerged on their base branch and for which a review has been requested through the API.

**Comment by obazoud** [comment]
@ratibus @KuiKui ok thanks. Maybe I misunderstood Crew workflow.
