### ISSUE TITLE
wiki - installation - apache mod headers missing

### ISSUE THREAD

**Issue by bmontuelle** [crew-cr/Crew#129]
Hi, 

I'm juste trying to use crew on my workstation. I didnt have apache mod_headers installed and the vhost configuration given at https://github.com/pmsipilot/Crew/wiki/How-to-install-Crew is failing on line "Header append Vary User-Agent env=!dont-vary"

Perhaps you should add another Ifmodule condition inside the first one or precise apache required module, something like this works for me
    <IfModule mod_deflate.c>
            BrowserMatch ^Mozilla/4 no-gzip
            BrowserMatch \bMSIE\s7 !no-gzip
            BrowserMatch \bMSIE.*SV !no-gzip
            BrowserMatch \bOpera !no-gzip
            SetOutputFilter DEFLATE
        <IfModule mod_headers.c>
            Header append Vary User-Agent env=!dont-vary
        </IfModule>
    </IfModule>

Thanks

**Comment by ratibus** [comment]
Hi

Thanks for your issue. I fixed the wiki page.

Regards
