### ISSUE TITLE
A good use guide?

### ISSUE THREAD

**Issue by kvnwolf** [crew-cr/Crew#135]
I've installed the project, and i've been able to clone a repo from my Github account. Now, when i commit and change/add/delete files, i go to the project, click on sync but nothing happens.

Any idea of what i'm doing grong?

**Comment by laurent22** [comment]
I think this project indeed needs a user guide. There's some info on how to install it, how to configure it, but nothing on how to actually use it. I understand there's some REST API to request code reviews but not obvious at all how or when to use it.

**Comment by DannyvdSluijs** [comment]
I've installed this application as well. The install and configuration docs are very helpful and clear. However I'm stuck on getting started on code reviewing. Trying to find an alternative to gerrit and would like to keep an open source variant iso crucible.
