### ISSUE TITLE
"Status" on a comment

### ISSUE THREAD

**Issue by pmartin** [crew-cr/Crew#24]
It would be nice if one could, especially when working a file for which more that reviewee will fix things :
- Mark a comment as "assigned" to himself _(so others don't start fixing something that's already being fixed)_
- Mark a comment as "fixed"
- Mark a comment as "won't fix"

**Comment by tentacode** [comment]
I don't know, comments are like discussion, it's not bug tracking here. Leave that to Redmine IMO. You can still write it directly in your comments.
