### ISSUE TITLE
Files are not ordered during the review

### ISSUE THREAD

**Issue by ratibus** [crew-cr/Crew#40]
Neither the blue flle list nor the "Next file" / "Previous file" seem to order files.

It's a bit confusing when you come from the branch view where files are ordered.

**Comment by srogier** [comment]
They seems to be sorted by file id.

It's confusing when you are in branch which have many reviews : the first file in the branch view could not be the file with the lowest file id. So when you do "Next file", you go to the file with next file id, and you don't see files with lower file id.
