### ISSUE TITLE
Comment : '>' in code => double-html-escape

### ISSUE THREAD

**Issue by pmartin** [crew-cr/Crew#94]
In a comment, I write this :

```
aaa `$blah->plop()` bbb
```

i.e. : I input a portion of code, with a `>` in it ; and I put all that between backticks, to highlight the fact that it's source-code -- and to have it presented as such.

The result I get when the comment is displayed, look like this :

```
aaa $blah-&gt;plop() bbb
```

Basically : the `>` I typed is displayed as `&gt;`
_(The `$blah-&gt;plop()` is displayed as code, which is OK -- I just didn't know how to show that here)_

There seems to be a bit too much of html-encoding in the code segments.

**Comment by KuiKui** [comment]
Je suis tristesse ![screenshot](http://img11.imageshack.us/img11/3031/capturedcran20120603155.png)
Cela ne viendrait-il pas de la configuration serveur ?

**Comment by pmartin** [comment]
_(Maintenant que tu es parti sur du français, je reste sur du français ^^ )_

Je ne sais pas exactement comment marche le système d'escaping en sortie de sf, mais c'est à priori là-dessus qu'il faut jouer.

Dans `_commentLine.php` ligne `16`, il y a cet appel :

```
<?php echo Markdown($comment->getValue()) ?>
```

C'est ça qui permet d'afficher le commentaire.

Problème : le texte reçu par la fonction `Markdown()` est déjà échappé une première fois : il contient `&gt;` _(je viens de tester sur ma machine)_, et pas `>`
Vu que l'encodeur Markdown refait une passe d'échappement => on se retrouve avec un double-escaping HTML.

En possibilité de solution "brutale", on peut désactiver l'escaping automatique de sf pour le texte du commentaire, en remplaçant l'appel vu plus haut par celui-ci :

```
<?php echo Markdown($comment->getValue(ESC_RAW)) ?>
```

De la sorte, sf n'échappe pas le HTML ; et le parseur Markdown se retrouve seul chargé de l'échappement en sortie.

Après, ça peut avoir comme effet d'autoriser "trop" de code HTML, menant possiblement à n'importe quel type d'injection -- donc, je ne fais pas une PR avec ce "correctif", qui est peut-être à compléter.
Une possibilité pour compléter serait de passer un coup de HTML Purifier _(ou autre outil équivalent)_ sur ce que retourne `Markdown()` ; pour spécifier nous-même quelles sont les balises et attributs HTML que l'on autorise ; avec ça, on réduit les possibilités d'injection _(pour des commentaires, sur cette appli, il doit y avoir à tout casser 8 ou 10 balises HTML à autoriser, grand maximum)_
